src/OpenConext/Profile/Entity/User.php
<?php

declare(strict_types = 1);

/**
 * Copyright 2015 SURFnet B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace OpenConext\Profile\Entity;

use OpenConext\Profile\Api\ApiUserInterface;
use OpenConext\Profile\Value\ContactEmailAddress;
use OpenConext\Profile\Value\Locale;
use Surfnet\SamlBundle\SAML2\Attribute\AttributeSet;
use Symfony\Component\Security\Core\User\UserInterface;

final class User implements ApiUserInterface
{
    private ?ContactEmailAddress $supportContactEmail = null;

    public function __construct(
        private readonly AuthenticatedUser $authenticatedUser,
        private Locale                     $locale,
    ) {
    }

    /**
     * @return UserInterface
     */
    public function withSupportContactEmail(
        ContactEmailAddress $supportContactEmail,
    ): UserInterface|User {
        $newUser = clone $this;
        $newUser->supportContactEmail = $supportContactEmail;

        return $newUser;
    }

    public function switchLocaleTo(
        Locale $locale,
    ): void {
        $this->locale = $locale;
    }

    public function hasSupportContactEmail(): bool
    {
        return $this->supportContactEmail !== null;
    }

    public function getSupportContactEmail(): ?ContactEmailAddress
    {
        return $this->supportContactEmail;
    }

    public function getLocale(): Locale
    {
        return $this->locale;
    }

    public function getAttributes(): AttributeSet
    {
        return $this->authenticatedUser->getAttributesFiltered();
    }

    public function getId(): string
    {
        return $this->authenticatedUser->getNameId();
    }
}

templates/layout/main/flashMessages.html.twig
{% if app.session.flashbag is not empty %}
    {% for type, messages in app.session.flashBag %}
        {% for message in messages %}
            <div class="toast">
                <p>
                    {% if type == 'success' %}
                        <i class="fa fa-check"></i>
                    {% elseif type == 'error' %}
                        <i class="fa fa-exclamation-triangle"></i>
                    {% endif %}
                    {{ message|trans }}
                </p>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/layout/main/navigation.html.twig
{% set route = app.request.attributes.get('_route') %}
<nav class="navigation" aria-labelledby="main-nav-label">
    <h2 class="visually-hidden" id="main-nav-label">{{ 'accessibility.nav.title'|trans }}</h2>
    <button
        aria-haspopup="menu"
        aria-pressed="false"
        class="navigation__mobileButton"
        type="button"
    >
        <span class="visually-hidden">
            {{ 'accessibility.nav.title'|trans }}
        </span>
        {% include "@OpenConextProfile/svgs/arrow.svg" with { className: 'navigation__mobileIcon' } %}
    </button>
    <ul
        class="navigation__list"
    >
        {% set isActive = route == 'profile.introduction_overview' %}
        <li class="navigation__item navigation__home{% if isActive %} active{% endif %}">
            <a{% if isActive %} aria-current="page"{% endif %} class="navigation__link navigation__link-first{% if isActive %} active{% endif %}" href="{{ path('profile.introduction_overview') }}">
                {{ 'profile.introduction.short_title'|trans }}
            </a>
        </li>
        {% set isActive = route == 'profile.my_profile_overview' %}
        <li class="navigation__item navigation__myProfile{% if isActive %} active{% endif %}">
            <a{% if isActive %} aria-current="page"{% endif %} class="navigation__link{% if isActive %} active{% endif %}" href="{{ path('profile.my_profile_overview') }}">
                {{ 'profile.my_profile.short_title'|trans }}
            </a>
        </li>
        {% if navigation_invite_roles_enabled %}
            {% set isActive = route == 'profile.invite_roles' %}
            <li class="navigation__item  navigation__inviteRoles{% if isActive %} active{% endif %}">
                <a{% if isActive %} aria-current="page"{% endif %} class="navigation__link{% if isActive %} active{% endif %}" href="{{ path('profile.invite_roles') }}">
                    {{ 'profile.invite_roles.short_title'|trans }}
                </a>
            </li>
        {% endif %}
        {% set isActive = route == 'profile.my_surf_conext_overview' %}
        <li class="navigation__item navigation__mySurf{% if isActive %} active{% endif %}">
            <a{% if isActive %} aria-current="page"{% endif %} class="navigation__link{% if isActive %} active{% endif %}" href="{{ path('profile.my_surf_conext_overview') }}">
                {{ 'profile.my_surf_conext.short_title'|trans }}
            </a>
        </li>
        {% set isActive = route == 'profile.my_services_overview' %}
        <li class="navigation__item navigation__myServices{% if isActive %} active{% endif %}">
            <a{% if isActive %} aria-current="page"{% endif %} class="navigation__link{% if isActive %} active{% endif %}" href="{{ path('profile.my_services_overview') }}">
            {{ 'profile.my_services.short_title'|trans }}
            </a>
        </li>
        {% set isActive = route == 'profile.my_connections_overview' %}
        <li class="navigation__item  navigation__myConnections{% if isActive %} active{% endif %}">
            <a{% if isActive %} aria-current="page"{% endif %} class="navigation__link navigation__link-last{% if isActive %} active{% endif %}" href="{{ path('profile.my_connections_overview') }}">
                {{ 'profile.my_connections.short_title'|trans }}
            </a>
        </li>
    </ul>
</nav>